let moment = require("moment")
let lodash = require("lodash")

// console.log(`${moment().format('MMMM Do YYYY, h:mm:ss a')}`)
// console.log(`${moment().format('dddd')}`)
// console.log(`${moment().format("MMM Do YY")}`)
// console.log(new moment(`2020-01-01`))
// console.log(new moment(`2020-14-01`))
// console.log(moment().add(7, 'months').calendar())
// console.log(moment().subtract(7, 'days').calendar())
// let a = moment([2020 - 01 - 01])
// let b = moment([2018 - 01 - 01])
// console.log((b.diff(a, `years`)))
// console.log(moment([2019]).isLeapYear())
// console.log(lodash.chunk(['a', 'b', 'c', 'd'], 3))
// console.log(lodash.compact([0, 1, false, 2, '', 3]))
// console.log(lodash.concat([1, 2], 2, [3], [[4]]))
// console.log(lodash.difference([2, 1, 5], [2, 3]))
// console.log(lodash.differenceBy([2.1, 1.2], [2.3, 3.4], Math.floor))
